- name: opkg update and install opkg dependencies
  #community.general.opkg?
  opkg:
    name: "{{ package }}"
    update_cache: yes
  loop: 
    - python
    - python-dev
    - python-setuptools
    - python-pip
    - gcc
  loop_control:
    loop_var: package

- name: Pip install python dependencies
  pip:
    name:
      - enum
      - typing
      - psutil
      - urllib3

# TODO: Add bluetooth.h and libbluetooth or w/e here


# - name: Copy Pybluez 0.22 to Device
#   copy: 
#     src: Pybluez-0.22.tar
#     dest: /root/

- name: Unpack Pybluez
  tar:
    src: Pybluez-0.22.tar
    dest: /root/

- name: Install Pybluez
  command: python /root/Pybluez/setup.py install

# Copy ipk files
# install all ipks